Carthage/Commandant

Commandant/Errors.swift

Indents every line of a multi-line usage description.

Multi-line usage descriptions

---

Cartfile
Cartfile.private

See https://github.com/Carthage/Carthage/pull/332.

Move xcconfigs to Cartfile.private

---

.travis.yml
Cartfile
Cartfile.private
Cartfile.resolved
Commandant/HelpCommand.swift
Commandant/Option.swift

Upgrade dependencies and Commandant itself for Swift 1.2b3.

Swift 1.2b3

---

.travis.yml
Cartfile.private
Cartfile.resolved

Addresses https://github.com/Carthage/Commandant/pull/31#issuecomment-142467074.

[Swift 2] Update Quick to work with xctool

---

.travis.yml
Cartfile
Cartfile.resolved

To match with https://github.com/Carthage/ReactiveTask/pull/37.

Update Result to 0.6.0-beta.5

---

Cartfile
Cartfile.resolved

I'm gonna release 0.7.0 after this is merged.

Update Result to 1.0

---

Commandant/ArgumentParser.swift
Commandant/Command.swift

See each commit for the details.

Some cleanups for the codebase

---

.travis.yml

This might be required since there is SPM job too.
https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

Add a condition for `deploy.on` in .travis.yml

---

Cartfile.resolved

https://github.com/Quick/Quick/releases/tag/v0.9.1

Update Quick to v0.9.1

---

.travis.yml

[Travis] Minor tweak for deploy

---

Cartfile.private
Cartfile.resolved
Package.swift

Update Quick to v0.10.0

---

.travis.yml

Carthage is pre-installed on Travis.
https://travis-ci.org/Carthage/Commandant/jobs/174065654#L931-L933

[Travis] Fix `before_deploy`

---

Sources/Commandant/Argument.swift
Sources/Commandant/Option.swift
Sources/Commandant/Switch.swift

Please see the diffs without whitespace changes: https://github.com/Carthage/Commandant/pull/107/files?w=1

Implement operators as static functions where possible

---

.travis.yml

Older snapshots have been removed.

[CI] Use latest 4.0-DEVELOPMENT-SNAPSHOT

---

.travis.yml
Cartfile.private
Cartfile.resolved
Package.resolved
Package.swift

https://github.com/apple/swift-package-manager/blob/swift-4.0-branch/Documentation/PackageDescriptionV4.md

[SwiftPM] Use V4 PackageDescription

---

Commandant.xcodeproj/project.pbxproj
Sources/Commandant/ArgumentParser.swift
Sources/Commandant/OrderedSet.swift
Tests/CommandantTests/OrderedSetSpec.swift
Tests/LinuxMain.swift

Implement and use a poor man's `OrderedSet`

---

Tests/CommandantTests/OrderedSetSpec.swift

[OrderedSetSpec] Remove Set ordering expectation

---

Sources/Commandant/Command.swift

> warning: 'launchPath' is deprecated: renamed to 'executableURL'
> warning: 'launch()' is deprecated: renamed to 'run'

Fix deprecation warnings on Swift 5.0 for Linux

---

.hound.yml
.swiftlint.yml
Sources/Commandant/Command.swift
Sources/Commandant/HelpCommand.swift
Sources/Commandant/Option.swift
Tests/CommandantTests/OptionSpec.swift
Tests/CommandantTests/OptionsWithEnumProtocolSpec.swift

https://github.com/Carthage/Commandant/pull/146#discussion_r272675541

[lint] Add .swiftlint.yml, .hound.yml and address some violations

---

Cartfile.resolved

I didn’t notice this before merging.
https://github.com/Carthage/Commandant/pull/146#issuecomment-482610502
Thanks @ikesyo 🙏

Remove Result from Cartfile.resolved

---

Commandant.podspec
Sources/Commandant/Info.plist
Tests/CommandantTests/Info.plist

#146 
[Remove Result dependency by daltonclaybrook · Pull Request #146 · Carthage/Commandant](https://github.com/Carthage/Commandant/pull/146)
Bumped up version to 0.17.0

Release 0.17.0

---

.travis.yml
Cartfile.private
Cartfile.resolved
Commandant.xcodeproj/project.pbxproj
Commandant.xcodeproj/xcshareddata/xcschemes/Commandant.xcscheme
Package.resolved

- xcconfigs (1.0)
- Quick (2.2.1)
- Nimble (8.1.1)

⬆️ Update dev dependencies
