- Commandant/Errors.swift
*Related to #17*
Based off [this comment.](https://github.com/Carthage/Commandant/pull/17#discussion_r24301394)
[Apple’s documentation for `newlineCharacterSet`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSCharacterSet_Class/index.html#//apple_ref/occ/clm/NSCharacterSet/newlineCharacterSet)
> Separate multi-line usage description with `newlineCharacterSet`.

- Cartfile
- Cartfile.private
These aren't actually dependencies of Commandant, and are only used for 
testing. We shouldn't list them with the actual dependencies.
> Move testing dependencies to private Cartfile

- .gitmodules
- Cartfile
- Cartfile.private
- Cartfile.resolved
- Commandant/ArgumentParser.swift
- Commandant/Command.swift
- Commandant/Errors.swift
- Commandant/HelpCommand.swift
- Commandant/Option.swift
- CommandantTests/OptionSpec.swift
Updates to LlamaKit’s parameterized errors.
Note that this still uses Swift 1.1.
> Upgrade dependencies

- Commandant.xcodeproj/project.pbxproj
- Commandant/ArgumentParser.swift
- Commandant/Errors.swift
- Commandant/Option.swift
- Commandant/Switch.swift
- CommandantTests/OptionSpec.swift
Resolves #1. I plan to look at #3 as well but that depends on this change.
The one thing this doesn't handle perfectly is mixing short and long flags. It's biased to the last long form flag rather than the last of either. I expect this is probably fine though.
> Single character flags

- Commandant/ArgumentParser.swift
- Commandant/Command.swift
- Commandant/Errors.swift
- Commandant/HelpCommand.swift
- Commandant/Option.swift
- CommandantTests/OptionSpec.swift
This allows clients to pass through errors that occur when running their commands.
/cc @jpsim who asked about this in chat a while ago, I think
> Parameterize CommandantError by a ClientError type

- Cartfile.resolved
- Commandant/ArgumentParser.swift
Seemingly there was undocumented semantic change to stdlib's `Array.split`, which caused the fail of one test. `maxCount` doesn't behave as documented. Passing `2` instead of `1` fixes the test.
```
Test Case '-[CommandantTests.OptionsTypeSpec CommandMode_Arguments__should_treat____as_the_end_of_valued_options_##_68]' started.
OptionSpec.swift:71: error: -[CommandantTests.OptionsTypeSpec CommandMode_Arguments__should_treat____as_the_end_of_valued_options_##_68] : failed - expected to equal <{ intValue: 42, stringValue: foobar, optionalFilename: filename, requiredName: --intValue }>, got <nil> (use beNil() to match nils)
```
> Update for Xcode 7 Beta 5

- Commandant/Command.swift
This adds:
```swift
@noreturn public func main(var arguments arguments: [String], defaultVerb: String, errorHandler: ClientError -> ())
```
In addition to the current:
```swift
@noreturn public func main(defaultVerb defaultVerb: String, errorHandler: ClientError -> ())
```
Which now just calls the new function with `Process.arguments` as the first parameter.
> Add CommandRegistry “main” with explicit arguments

- Commandant/Command.swift
Same as https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2484. :wink:
> Rename to AnyCommand to be consistent with the standard lib

- Commandant/Command.swift
- Commandant/Errors.swift
- Commandant/HelpCommand.swift
- Commandant/Option.swift
- CommandantTests/OptionSpec.swift
- README.md
This introduces some breaking changes to try to simplify the interaction of `CommandType` and `OptionsType`:
- Add a `typealias Options: OptionsType` to `CommandType`
- Make `ClientError`s conform to `ErrorType`
- Parse options from `OptionsType`s automatically
- Change `CommandType.run()` to take `Options` instead of `CommandMode`
- Don't make `AnyCommand` conform to `CommandType`
- Add `AnyCommand.usage()`
This would greatly simplify something like #40 because options are no longer parsed by commands. It also removes a decent amount of boilerplate from commands.
> Give Commands Options

- Commandant/ArgumentParser.swift
- Commandant/Command.swift
- Commandant/Errors.swift
This is based on the implementations of #34 and #41. Resolves #2.
~~If a command specifies its associated options type in its `public typealias Options = ...` when that is `OptionsType`, the options will be evaluated and validated before the actual command runs.~~
/cc @norio-nomura, @mdiep
> Generate an error against unrecognized arguments

- Commandant.xcodeproj/project.pbxproj
- Commandant/Argument.swift
- Commandant/ArgumentType.swift
- Commandant/Errors.swift
- Commandant/HelpCommand.swift
- Commandant/Option.swift
- CommandantTests/OptionSpec.swift
This is needed at https://github.com/Carthage/Carthage/pull/972#issuecomment-164314514.
- A positional argument is represented as `Argument` now.
- If `Argument` is tied to a property of `Array<ArgumentType>` type, that consumes the rest of positional arguments entirely.
- `Option.key` is non-optional now.
> Introduce `Argument` type which can handle an argument list

- Commandant/Command.swift
The `ClientError` from `CommandType.run` is discarded.
> Fix error handling in CommandWrapper

- Commandant.xcodeproj/project.pbxproj
- Commandant/Command.swift
- Commandant/HelpCommand.swift
- CommandantTests/CommandSpec.swift
This avoids force unwrapping of error in `usage` closure. Some options may return `.Success` case for `CommandMode.Usage` (e.g. `NoOptions`).
Sould fix https://github.com/realm/SwiftLint/pull/312#issuecomment-168558053.
> Fix crash in `help` command

- Commandant/Command.swift
See https://github.com/Carthage/Carthage/issues/1017 for the context.
> Cargo in particular has a plugin architecture, which led to the formation of a bunch of useful sub-commands.
> I think carthage would greatly benefit from the addition of either support for similar plugins or the addition of similar sub-commands by default.
> Implement subcommand mechanism

- Sources/Commandant/Option.swift
Why was this not exposed earlier?
> Expose a public initializer to NoOptions so that tests can be written for commands that take NoOptions

- .travis.yml
- Cartfile.private
- Cartfile.resolved
- Commandant.xcodeproj/project.pbxproj
- Sources/Commandant/Command.swift
- Sources/Commandant/Option.swift
- Tests/OptionSpec.swift
~~This is another breaking change because of the `associatedtype` usage.~~
Updated `Nimble` to be built with Xcode 7.3.
> Swift 2.2 support

- Sources/Commandant/Errors.swift
- Sources/Commandant/Option.swift
- Tests/OptionSpec.swift
In https://github.com/Carthage/Carthage/pull/1143, it would be nice to use an `Option<String?>` for a command-line option. Since the default value isn't really known, it would be preferable to default to `nil`. This PR makes that possible, **but it introduces a breaking change**.
* Make `Option` require a `defaultValue`. Previously, a `nil` default meant that the parameter was required. Carthage doesn't use this, and I think that behavior is a little silly given that it's called _option_. If this behavior is required somewhere, I'd rather see another type added.
* Make a version of `<|` that works with an `Option<T?>` where `T: ArgumentType`.
The implementation isn't as nice as I'd like. I ran into Swift limitations, segfaults, and, I think, some type inference errors. But ultimately I …
> Make Option work with Optionals

- .travis.yml
- Commandant.xcodeproj/project.pbxproj
- Package.swift
- Sources/Commandant/ArgumentParser.swift
- Sources/Commandant/Command.swift
- Sources/Commandant/Errors.swift
- Sources/Commandant/HelpCommand.swift
- Sources/Commandant/Option.swift
- Sources/Commandant/Swift3to22.swift
- Use wrapper that converting from Swift 3.0 API to Swift 2.2 API.
- Use `swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a`
- Add `swift build` on Linux to Travis-CI
> Swift 3.0 compatibility

- Sources/Commandant/Command.swift
- Sources/Commandant/Errors.swift
This will provide better migration support to 0.11.x on Xcode.
> Add missing `@available`s to enums

- Package.swift
it's implicitly included when Quick is pulled in. Resolves #79.
> remove Nimble from Package.swift

- .travis.yml
This is likely why https://github.com/Carthage/Commandant/releases/tag/0.11.2 (and 0.11.1) didn't get `Commandant.framework.zip` automatically attached.
> fix travis deploy by specifying to run when JOB=Xcode8

- .Package.test.swift
- .travis.yml
We still run `swift test` on CI using separated `.Package.test.swift`.
Should fix #82.
> [SwiftPM] Remove test dependencies from `Package.swift`

- Cartfile
- Cartfile.resolved
- Package.swift
Just update Result to 3.1.0.
Ref: https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Cartfile#L1
> Bump Result version to 3.1.0

- Sources/Commandant/Switch.swift
- Tests/CommandantTests/OptionSpec.swift
See #95 
Added 3 tests - one for existing behavior, and 2 new tests for the bug I refer to.
> Fix switch keys being ignored when a Switch contains a flag

- Sources/Commandant/Command.swift
I ran into an issue with a project that uses *Commandant* where the default verb is not used if if any options/arguments are present.
For example:
```
swiftlint lint --path . // runs lint command ok
swiftlint --path . // fails since the --path argument prevents the default command from being used
```
This can also be seen with carthage as well:
```
carthage // run default command: help
carthage help --help // fails with: Unrecognized arguments: --help
carthage --use-ssh // fails with: Unrecognized command: '--use-ssh'. See `carthage help`.
```
The argument should not overwrite the default command and this PR addresses that issue.
Let me know if you have any questions or comments. Thanks!
> use default command if options are present

- Sources/Commandant/Command.swift
```swift
registry
.register(FooCommand())
.register(BarCommand())
.register(BazCommand())
```
> [CommandRegistry] Return self from `register(_:)` for method chaining

- Commandant.xcodeproj/project.pbxproj
- Sources/Commandant/ArgumentProtocol.swift
- Tests/CommandantTests/OptionsWithEnumProtocolSpec.swift
- Tests/LinuxMain.swift
Hi.
This PR will allow making strict arguments values in a more comfortable way.
Problem:
&nbsp;&nbsp;Having: 2 projects, 4 deployment environments.
&nbsp;&nbsp;Task: download resources for concrete one project & one environment.
&nbsp;&nbsp;Problem: Should get string parameter, make init(rawValue: _), check if `nil`, throw an error.
With this PR we will get `RawRepresentable` arguments (where `RawValue` is `StringProtocol` or `FixedWidthInteger`) from the box:
```swift
enum DeploymentEnvironment: String, ArgumentProtocol {
static let name: String = "Deployment environment"
case dev, qa, stage, release
}
enum Project: String, ArgumentProtocol {
static let name: String = "Project"
case projectA, projectB
}
struct DownloadResourcesOptions: OptionsProtocol {
let project: Project
let …
```
> Strict arguments values support.

- Sources/Commandant/Argument.swift
- Sources/Commandant/Errors.swift
This fixes #128 by displaying the `usageParameter` when it's available. On a Swiftlint branch where I'm testing this out for a new paths `Argument`, it resulted in a help message like this:
```
[<paths…>]
list of paths to the files or directories to lint
```
> Improve Argument help message

- Commandant.podspec
In the initial version of the spec, I missed that [0.14 actually depends on Result 3.2](https://github.com/Carthage/Commandant/pull/132#discussion_r200534809).
> ⬇️ Fix Result version in podspec

- .travis.yml
- Commandant.podspec
- Sources/Commandant/Info.plist
- Tests/CommandantTests/Info.plist
Making one last release supporting Swift ~4.1~ 4.2 & 5.0 before requiring Swift 5.0 with #146.
> Release 0.16.0
